### ISSUE TITLE
Can't train xgboost models as part of a workflow involving non-numeric data

### ISSUE THREAD

**Issue by TylerGrantSmith** [tidymodels/workflows#151] opened 2022-05-05 18:27 UTC
While attempting to test the new case weights I think I uncovered a bug with training xgboost models as part of a workflow. 

It appears that this happens because the one-hot encoding happens when training the model with a formula provided.  In the workflow, the formula (specified in the recipe) is not supplied when training the model.

``` r
library(tidymodels)
#> Warning: package 'tidymodels' was built under R version 4.0.5
#> -- Attaching packages -------------------------------------- tidymodels 0.1.4 --
#> v broom        0.7.12         v recipes      0.2.0.9001
#> v dials        0.1.0          v rsample      0.1.1     
#> v dplyr        1.0.8          v tibble       3.1.6     
#> v ggplot2      3.3.5          v tidyr        1.2.0     
#> v infer        1.0.0          v tune         0.2.0.9001
#> v modeldata    0.1.1.9000     v workflows    0.2.6.9001
#> v parsnip      0.2.1.9001     v workflowsets 0.1.0     
#> v purrr        0.3.4          v yardstick    0.0.9.9000
#> Warning: package 'broom' was built under R version 4.0.5
#> Warning: package 'dials' was built under R version 4.0.5
#> Warning: package 'dplyr' was built under R version 4.0.5
#> Warning: package 'ggplot2' was built under R version 4.0.5
#> Warning: package 'infer' was built under R version 4.0.5
#> Warning: package 'rsample' was built under R version 4.0.5
#> Warning: package 'tibble' was built under R version 4.0.5
#> Warning: package 'tidyr' was built under R version 4.0.5
#> Warning: package 'workflowsets' was built under R version 4.0.5
#> -- Conflicts ----------------------------------------- tidymodels_conflicts() --
#> x purrr::discard() masks scales::discard()
#> x dplyr::filter()  masks stats::filter()
#> x dplyr::lag()     masks stats::lag()
#> x recipes::step()  masks stats::step()
#> * Learn how to get started at https://www.tidymodels.org/start/
set.seed(1)
x <- sim_classification(5000) %>% mutate(non_numeric = rep(c("a","b"), n() / 2))

xgb_spec <- 
  boost_tree() %>% 
  set_mode("classification") %>% 
  set_engine("xgboost")

# training the model works with formula specified
fit(xgb_spec, formula = class ~ ., data = x)
#> [13:21:34] WARNING: amalgamation/../src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
#> parsnip model object
#> 
#> ##### xgb.Booster
#> raw: 103.2 Kb 
#> call:
#>   xgboost::xgb.train(params = list(eta = 0.3, max_depth = 6, gamma = 0, 
#>     colsample_bytree = 1, colsample_bynode = 1, min_child_weight = 1, 
#>     subsample = 1, objective = "binary:logistic"), data = x$data, 
#>     nrounds = 15, watchlist = x$watchlist, verbose = 0, nthread = 1)
#> params (as set within xgb.train):
#>   eta = "0.3", max_depth = "6", gamma = "0", colsample_bytree = "1", colsample_bynode = "1", min_child_weight = "1", subsample = "1", objective = "binary:logistic", nthread = "1", validate_parameters = "TRUE"
#> xgb.attributes:
#>   niter
#> callbacks:
#>   cb.evaluation.log()
#> # of features: 17 
#> niter: 15
#> nfeatures : 17 
#> evaluation_log:
#>     iter training_logloss
#>        1         0.570675
#>        2         0.486232
#> ---                      
#>       14         0.178386
#>       15         0.168512

sim_rec <- recipe(class ~ ., data = x)

xgb_wflow <- 
  workflow() %>% 
  add_recipe(sim_rec) %>% 
  add_model(xgb_spec) 

# training the workflow fails
xgb_res <- xgb_wflow %>% fit(data = x)
#> Error in `maybe_matrix()`:
#> ! Some columns are non-numeric. The data cannot be converted to numeric matrix: 'non_numeric'.
```

<sup>Created on 2022-05-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by EmilHvitfeldt** [comment] 2022-05-05 19:03
Hello @TylerGrantSmith 👋 

This is expected behavior since {xgboost} doesn't handle non-numeric values directly, please see [boost_tree() xgboost documentation](https://parsnip.tidymodels.org/reference/details_boost_tree_xgboost.html#preprocessing-requirements) for more information. When using the formula method via [fit.model_spec()](https://parsnip.tidymodels.org/reference/fit.html), parsnip will convert factor columns to indicators using a one-hot encoding. When using workflows more checking is being performed, hence the error.

We recommend that you explicitly convert non-numeric variables to numeric variables in the recipe when using xgboost in a workflow.

**Comment by TylerGrantSmith** [comment] 2022-05-05 19:07
@EmilHvitfeldt  

Alright, thanks.  Is that caveat explained anywhere in the workflows documentation?  It is surprising to me that the two methods would behave differently.

**Comment by DavisVaughan** [comment] 2022-05-05 19:47
If you use `add_formula()` rather than `add_recipe()`, this works out of the box because `add_formula()` runs `model.matrix()`, like what happens when you fit with the parsnip model directly with `fit(xgb_spec, formula = class ~ ., data = x)`.

```r
library(tidymodels)

set.seed(1)
x <- sim_classification(5000) %>% mutate(non_numeric = rep(c("a","b"), n() / 2))

xgb_spec <- 
  boost_tree() %>% 
  set_mode("classification") %>% 
  set_engine("xgboost")

xgb_wflow <- 
  workflow() %>% 
  add_formula(class ~ .) %>% 
  add_model(xgb_spec) 

xgb_res <- xgb_wflow %>% 
  fit(data = x)

xgb_res
#> ══ Workflow [trained] ══════════════════════════════════════════════════════════
#> Preprocessor: Formula
#> Model: boost_tree()
#> 
#> ── Preprocessor ────────────────────────────────────────────────────────────────
#> class ~ .
#> 
#> ── Model ───────────────────────────────────────────────────────────────────────
#> ##### xgb.Booster
#> raw: 64.8 Kb 
#> call:
#>   xgboost::xgb.train(params = list(eta = 0.3, max_depth = 6, gamma = 0, 
#>     colsample_bytree = 1, colsample_bynode = 1, min_child_weight = 1, 
#>     subsample = 1, objective = "binary:logistic"), data = x$data, 
#>     nrounds = 15, watchlist = x$watchlist, verbose = 0, nthread = 1)
#> params (as set within xgb.train):
#>   eta = "0.3", max_depth = "6", gamma = "0", colsample_bytree = "1", colsample_bynode = "1", min_child_weight = "1", subsample = "1", objective = "binary:logistic", nthread = "1", validate_parameters = "TRUE"
#> xgb.attributes:
#>   niter
#> callbacks:
#>   cb.evaluation.log()
#> # of features: 17 
#> niter: 15
#> nfeatures : 17 
#> evaluation_log:
#>     iter training_logloss
#>        1        0.5706789
#>        2        0.4862339
#> ---                      
#>       14        0.1783856
#>       15        0.1685122
```

You have to kind of remember that the formula used in recipes does a different thing than the one used in workflows/parsnip:

- `fit(xgb_spec, formula = class ~ ., data = x)` runs `model.matrix()`, converting factors to dummy columns
- `add_formula(class ~ .)` runs `model.matrix()`, converting factors to dummy columns
- `recipe(class ~ .)` just selects `class` as the outcome and all other columns as predictors, with no extra transformations

So, as Emil said, you have to use `step_dummy()` in recipes if you'd like to also have factors converted to dummy columns there, which is required by xgboost.

The recipes docs talk about the `formula` argument here, which mentions that you shouldn't use any inline formulas or interaction terms there, because it is only doing selection. https://recipes.tidymodels.org/reference/recipe.html

**Comment by TylerGrantSmith** [comment] 2022-05-05 20:23
@DavisVaughan  Thanks for the suggestion, I did figure that as well.  Unfortunately the `add_formula` option fails when you also need to do other transformations requiring a `recipe` because it won't let you add both a formula and a recipe.

``` r
library(tidymodels)

set.seed(1)
x <- sim_classification(5000) %>% mutate(non_numeric = rep(c("a","b"), n() / 2))

xgb_spec <- 
  boost_tree() %>% 
  set_mode("classification") %>% 
  set_engine("xgboost")

sim_rec <- 
  recipe(class ~ ., data = x) %>% 
  step_normalize(all_numeric_predictors())
  # step_dummy(all_nominal(), one_hot = TRUE)

xgb_wflow <- 
  workflow() %>% 
  add_recipe(sim_rec) %>% 
  add_formula(class ~ .) %>% 
  add_model(xgb_spec) 
#> Error in `add_formula()`:
#> ! A formula cannot be added when a recipe already exists.
```

**Comment by DavisVaughan** [comment] 2022-05-05 20:26
Yea, you can only choose one "preprocessor", a formula or recipe. So if you want to use a recipe for other steps, then you'll have to generate dummy variable with `step_dummy()`.

**Comment by DavisVaughan** [comment] 2022-05-05 20:29
Also, `?parsnip::details_boost_tree_xgboost` documents the xgboost behavior in the "Preprocessing requirements" section, so I'd say there probably isn't any more documentation that we need to add. I am going to close this issue at this point, because it is not a bug and we don't seem to need more docs, but I appreciate you reaching out and asking about it!

**Closed by DavisVaughan** 2022-05-05 20:29 UTC
