### ISSUE TITLE
Predict doesn't work for recipe that modify outcome

### ISSUE THREAD

**Issue by mgirlich** [tidymodels/workflows#63] opened 2020-08-05 08:24 UTC
I modified the example in the help page of `predict.workflow()` so that `step_log()` is applied to the outcome variable `mpg` instead of `disp`. Unfortunately, this doesn't work but errors (this might be due to the breaking changes in [tibble 3.0](https://github.com/tidyverse/tibble/blob/master/NEWS.md#tibble-300): Error: Assigned data ... must be compatible with ...)

``` r
library(parsnip)
library(recipes)
#> Loading required package: dplyr
#> Warning: package 'dplyr' was built under R version 4.0.2
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step
library(magrittr)
library(workflows)

training <- mtcars[1:20,]
testing <- mtcars[21:32,]

model <- linear_reg() %>%
  set_engine("lm")

workflow <- workflow() %>%
  add_model(model)

recipe <- recipe(mpg ~ cyl + disp, training) %>%
  step_log(mpg)

workflow <- add_recipe(workflow, recipe)

fit_workflow <- fit(workflow, training)

predict(fit_workflow, testing)
#> Error: Assigned data `log(new_data[[col_names[i]]] + object$offset, base = object$base)` must be compatible with existing data.
#> x Existing data has 12 rows.
#> x Assigned data has 0 rows.
#> ℹ Only vectors of size 1 are recycled.
```

<sup>Created on 2020-08-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.0.1 (2020-06-06)
#>  os       macOS Catalina 10.15.6      
#>  system   x86_64, darwin17.0          
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       UTC                         
#>  date     2020-08-05                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date       lib source        
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.0.0)
#>  backports     1.1.8      2020-06-17 [1] CRAN (R 4.0.1)
#>  callr         3.4.3      2020-03-28 [1] CRAN (R 4.0.0)
#>  class         7.3-17     2020-04-26 [1] CRAN (R 4.0.1)
#>  cli           2.0.2      2020-02-28 [1] CRAN (R 4.0.0)
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 4.0.0)
#>  desc          1.2.0      2018-05-01 [1] CRAN (R 4.0.0)
#>  devtools      2.3.1      2020-07-21 [1] CRAN (R 4.0.1)
#>  digest        0.6.25     2020-02-23 [1] CRAN (R 4.0.0)
#>  dplyr       * 1.0.1      2020-07-31 [1] CRAN (R 4.0.2)
#>  ellipsis      0.3.1      2020-05-15 [1] CRAN (R 4.0.0)
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 4.0.0)
#>  fansi         0.4.1      2020-01-08 [1] CRAN (R 4.0.0)
#>  fs            1.5.0      2020-07-31 [1] CRAN (R 4.0.2)
#>  generics      0.0.2      2018-11-29 [1] CRAN (R 4.0.0)
#>  glue          1.4.1      2020-05-13 [1] CRAN (R 4.0.0)
#>  gower         0.2.2      2020-06-23 [1] CRAN (R 4.0.1)
#>  hardhat       0.1.4      2020-07-02 [1] CRAN (R 4.0.1)
#>  highr         0.8        2019-03-20 [1] CRAN (R 4.0.0)
#>  htmltools     0.5.0      2020-06-16 [1] CRAN (R 4.0.1)
#>  ipred         0.9-9      2019-04-28 [1] CRAN (R 4.0.0)
#>  knitr         1.29       2020-06-23 [1] CRAN (R 4.0.1)
#>  lattice       0.20-41    2020-04-02 [1] CRAN (R 4.0.1)
#>  lava          1.6.7      2020-03-05 [1] CRAN (R 4.0.0)
#>  lifecycle     0.2.0      2020-03-06 [1] CRAN (R 4.0.0)
#>  lubridate     1.7.9      2020-06-08 [1] CRAN (R 4.0.1)
#>  magrittr    * 1.5        2014-11-22 [1] CRAN (R 4.0.0)
#>  MASS          7.3-51.6   2020-04-26 [1] CRAN (R 4.0.1)
#>  Matrix        1.2-18     2019-11-27 [1] CRAN (R 4.0.1)
#>  memoise       1.1.0      2017-04-21 [1] CRAN (R 4.0.0)
#>  nnet          7.3-14     2020-04-26 [1] CRAN (R 4.0.1)
#>  parsnip     * 0.1.3      2020-08-04 [1] CRAN (R 4.0.1)
#>  pillar        1.4.6      2020-07-10 [1] CRAN (R 4.0.1)
#>  pkgbuild      1.1.0      2020-07-13 [1] CRAN (R 4.0.1)
#>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.0.0)
#>  pkgload       1.1.0      2020-05-29 [1] CRAN (R 4.0.0)
#>  prettyunits   1.1.1      2020-01-24 [1] CRAN (R 4.0.0)
#>  processx      3.4.3      2020-07-05 [1] CRAN (R 4.0.0)
#>  prodlim       2019.11.13 2019-11-17 [1] CRAN (R 4.0.0)
#>  ps            1.3.3      2020-05-08 [1] CRAN (R 4.0.0)
#>  purrr         0.3.4      2020-04-17 [1] CRAN (R 4.0.1)
#>  R6            2.4.1      2019-11-12 [1] CRAN (R 4.0.0)
#>  Rcpp          1.0.5      2020-07-06 [1] CRAN (R 4.0.1)
#>  recipes     * 0.1.13     2020-06-23 [1] CRAN (R 4.0.1)
#>  remotes       2.2.0      2020-07-21 [1] CRAN (R 4.0.1)
#>  rlang         0.4.7      2020-07-09 [1] CRAN (R 4.0.1)
#>  rmarkdown     2.3        2020-06-18 [1] CRAN (R 4.0.1)
#>  rpart         4.1-15     2019-04-12 [1] CRAN (R 4.0.1)
#>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 4.0.0)
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 4.0.0)
#>  stringi       1.4.6      2020-02-17 [1] CRAN (R 4.0.0)
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 4.0.0)
#>  survival      3.2-3      2020-06-13 [1] CRAN (R 4.0.1)
#>  testthat      2.3.2      2020-03-02 [1] CRAN (R 4.0.0)
#>  tibble        3.0.3      2020-07-10 [1] CRAN (R 4.0.1)
#>  tidyr         1.1.1      2020-07-31 [1] CRAN (R 4.0.2)
#>  tidyselect    1.1.0      2020-05-11 [1] CRAN (R 4.0.0)
#>  timeDate      3043.102   2018-02-21 [1] CRAN (R 4.0.0)
#>  usethis       1.6.1      2020-04-29 [1] CRAN (R 4.0.0)
#>  vctrs         0.3.2      2020-07-15 [1] CRAN (R 4.0.1)
#>  withr         2.2.0      2020-04-20 [1] CRAN (R 4.0.0)
#>  workflows   * 0.1.2      2020-07-07 [1] CRAN (R 4.0.1)
#>  xfun          0.16       2020-07-24 [1] CRAN (R 4.0.2)
#>  yaml          2.2.1      2020-02-01 [1] CRAN (R 4.0.0)
#> 
#> [1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library
```

</details>

**Comment by juliasilge** [comment] 2020-08-05 18:01
We probably need to think through what to do about applying recipe steps to outcomes like this more carefully; it's been the cause of a lot of problems.

**Comment by topepo** [comment] 2020-08-06 01:13
@mgirlich When `predict()` is used, it only has access to the predictors (mirroring how this would work with new samples). Even if the outcome column is present, it is not exposed to the recipe. This is generally a good idea so that we can avoid _information leakage_. 

One approach is the use the `skip = TRUE` option in `step_log()` so that it will avoid that step during `predict()` and/or `bake()`. However, if you are using this recipe with the `tune` package, there will still be an issue because the metric function(s) would get the predictions in log units and the observed outcome in the original units. 

The **better approach** is, for simple transformations like yours, to log the outcome outside of the recipe (before data analysis and the initial split). 

A lot of our earlier training materials used the outcome in the recipes (like you did) and we've been working on updating those to use pre-logging. The [workshop notes for this week](https://github.com/topepo/nyr-2020) have materials on this too. See slides 28-33 of the `Part_3.html` file for more discussion.

**Comment by mgirlich** [comment] 2020-08-06 06:00
@topepo Thanks for the explanation. After finding and understanding the issue I already thought that this might be the reason. Still, I was quite surprised as I never saw information about my issue.

Apart from training materials it would be great to

1. have some comment about that in the help files,
2. update the error message when using in-line functions in a formula

``` r
recipes::recipe(log(mpg) ~ disp)
#> Error: No in-line functions should be used here; use steps to define baking actions

# it would be nicer to have something like
#> Error: No in-line functions should be used here;
#> (i) mutate outcomes before applying a recipe
#> (ii) use steps to define baking actions on predictors
```

<sup>Created on 2020-08-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

What do you think about splitting the recipe in two phases: first the outcome steps where one can only modify the outcomes and second the prediction steps. I see the following advantages

a) no information leakage.
b) transformations are not accidentally applied to outcomes, e.g. when using `all_numeric()`. This happened to me a couple of times and I think this is an easy mistake to make. I'd assume that most of the steps should only be applied to the predictors anyway.
c) easy to understand.

Probably, you easily see a reason not to do it this way but it might be something to consider.

**Comment by DavisVaughan** [comment] 2020-09-02 18:06
I don't think there will be anything done in workflows for this, so I'm going to close this issue!

**Closed by DavisVaughan** 2020-09-02 18:06 UTC
Labels: bug

**Comment by jrosell** [comment] 2021-02-05 15:34
@topepo I found this exact error on https://rstudio-conf-2020.github.io/applied-ml/Part_3.html#48
