### ISSUE TITLE
add_formula(), set_encodings, predictor_indicators = none: Not passing date feature

### ISSUE THREAD

**Issue by mdancho84** [tidymodels/workflows#70] opened 2020-08-26 03:30 UTC
Using the development version of `modeltime`, I'm getting a hangup when combining a `workflow` with `add_formula()` where the formula has a date feature. It doesn't seem to be getting passed to the underlying function. 

```
library(tidymodels)
library(modeltime)
library(tidyverse)
library(lubridate)
library(timetk)

# Data
m750 <- m4_monthly %>% filter(id == "M750")

# Split Data 80/20
splits <- initial_time_split(m750, prop = 0.9)

# --- MODELS ---

model_spec_arima <- arima_reg() %>%
    set_engine(engine = "auto_arima") 

# --- WORKFLOW ---
workflow() %>% 
    add_model(model_spec_arima) %>% 
    add_formula(value ~ date) %>%  # <-- Error here
    fit(training(splits))
#>  Error: No date or date-time variable provided. Please supply a date or date-time variable as a predictor.
```

**Comment by mdancho84** [comment] 2020-08-26 03:31
I've referenced the initial issue here (business-science/modeltime#18) thinking I could resolve in Modeltime. I believe it may be inside workflows. Please let me know if I'm wrong though.

**Comment by DavisVaughan** [comment] 2020-08-31 13:26
I'm fairly certain this is a duplicate of https://github.com/tidymodels/workflows/issues/39, i.e. the date variables are being converted to numeric by `model.matrix()`. The dev version of workflows has `add_variables()` now, so this works:

(However, it hasn't been integrated into tune yet)

``` r
suppressPackageStartupMessages({
  library(tidymodels)
  library(modeltime)
  library(tidyverse)
  library(lubridate)
  library(timetk)
})

# Data
m750 <- m4_monthly %>% filter(id == "M750")

# Split Data 80/20
splits <- initial_time_split(m750, prop = 0.9)

# --- MODELS ---

model_spec_arima <- arima_reg() %>%
  set_engine(engine = "auto_arima") 

# --- WORKFLOW ---
workflow() %>% 
  add_model(model_spec_arima) %>% 
  add_variables(value, date) %>%
  fit(training(splits))
#> frequency = 12 observations per 1 year
#> ══ Workflow [trained] ══════════════════════════════════════════════════════════
#> Preprocessor: Variables
#> Model: arima_reg()
#> 
#> ── Preprocessor ────────────────────────────────────────────────────────────────
#> Outcomes: value
#> Predictors: date
#> 
#> ── Model ───────────────────────────────────────────────────────────────────────
#> Series: outcome 
#> ARIMA(0,1,1)(0,1,1)[12] 
#> 
#> Coefficients:
#>           ma1     sma1
#>       -0.3405  -0.4781
#> s.e.   0.0652   0.0628
#> 
#> sigma^2 estimated as 25114:  log likelihood=-1699.55
#> AIC=3405.1   AICc=3405.19   BIC=3415.8
```

<sup>Created on 2020-08-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Closed** 2020-08-31 13:26 UTC
Labels: bug

**Comment by mdancho84** [comment] 2020-08-31 13:34
Ah, gotcha - I saw that `workflows` was updated and assumed that the predictor encodings were integrated via `set_encoding()`.
